- name: TEST PROD Env
  hosts: frontends
  gather_facts: false
  tasks:

  - name: Curl website
    uri:
      url: "http://{{item}}"
      return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
    register: webpage

  - name: Fail if 'Ansible HOMEWORK has done its job' is not in the page content
    fail:
    when: "'Ansible HOMEWORK has done its job' not in webpage.results[0].content"
